---

logging:
  level:
    ROOT: info
    com.ferguson.cs: info

spring:
  main:
    allow-bean-definition-overriding: true
    datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://chico-db-dev.build.internal\CICDEV2
      username: wbsrvr_mmc
      password: 'Build12Dot24Cow!'
  mvc:
    favicon:
      enabled: false
  jmx:
    default-domain: com.build



info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"



  

