= Product Domain Services
Tyler Van Gorder <tyler.vangorder@build.com>
:toc: left
:sectlinks:
:sectanchors:
:stylesheet: asciidoctor.css
// If not rendered on github, we use fonts for the captions, otherwise, we assign github emojis. DO NOT PUT A BLANK LINE BEFORE THIS, the ICONS don't render.
ifndef::env-github[]
:icons: font
endif::[]
ifdef::env-github[]
:important-caption: :exclamation:
:warning-caption: :x:
:caution-caption: :hand:
:note-caption: :bulb:
:tip-caption: :mag:
endif::[]

This repository is the home of a domain service used to manage product data. This service will provide a central mechanism by which various product data feeds can be ingested and stored. It will also provide a mechanism for broadcasting product data changes through well-defined events. The resulting events will be fed to a messaging broker such that all downstream systems can subscribe and act upon those events.

WARNING: This is a work in progress and will be under constant change.

== Technology Decisions

This project is using architecture decision records to document some of the design decisions that have been made while developing this project. These records provide context for each decision and often provide links to more information.

link:docs/architecture/architecture-decisions.adoc[See this link for more details]


== Links

The following are useful links to help clarify domain terminology and design decisions made within the context of this service.

- https://docs.google.com/document/d/1ro6jKQwZFOGIfYMqxy9_bSAVALk10kNN5OaLdARDidA/edit?usp=sharing[The Product Service PRD]
- https://www.skuvault.com/blog/difference-between-product-options-and-product-variations[Product Options and Product Variations]
- https://www.skuvault.com/blog/product-kitting-alternates-for-ecommerce[Product Kitting]
- https://blog.datafeedwatch.com/how-to-find-the-gtins[GTIN]
- https://medium.com/scalia/5-classic-mistakes-of-master-product-data-management-b135138a08fd[Classic mistakes of master product data management]
- https://medium.com/scalia/the-dos-and-don-ts-of-product-taxonomy-e8b452c5dc78 [Do's and Dont's of Product Taxonomy]
- https://medium.com/scalia/why-scalia-decided-to-open-source-its-taxonomy-67e0cdf36d7d [Open Sourced Taxonomy]

== Assertions

- This service will have limited multi-tenant capabilities. A per-channel taxonomy can be used to filter which products are available on a given channel. If product data must be altered prior to sydnication to downstream systems, either multiple instances of this service must be used or the downstream listener must apply the mutations.
- The product data ingested into this service is assumed to already have been through the enrichment process.
- The storage mechanism for product data will not be visible to any systems external to the product service. This requirements means that the service must provide an API for getting data in/out of the underlying storage mechanism.
- The domain terminology defined by this service will be based off of industry standards.

== Core Product Data

The core product data is used to represent products that will be sold within an online store front. A "product" representations a family of closely related items called "variants" and defines all of the characteristics/attributes that are pertinent  to the product and its variants. Information that is common across the variants is represented at the product level while each unique variant will have a slightly different configuration of the product's characteristics. Variants represent the unique, sellable items and a user selects variants when adding things to their shopping cart. A product's manufacturer information is also represented at the product level.

- Products
- Product Variants
- Product Identifiers
- Product Attributes (Product characteristics)
- Product Options (Product customizations)
- Digital Assets (Images, pdfs, AR models, etc.)

=== Identifyng a Product and a Product Variant
A manufacturer and the manufacturer's assigned product ID are enough to identify a product family but a more specific identifier must be used to identify a product variant. The global identifier that is used by ferguson to reference a product variant is called an MPN (Master Product Number) ID. Additionally, there are alternate identifiers that can be assigned to a product variant and these identifiers are modeled as an identifier type ((GTIN, SKU, UPC, etc) and the actual identifier value.

=== Product Attributes
A product attribute is a characteristic of the product. The attribute's datatype, validation rules, and enumerated values are defined via a reusable, codified attribute definition.

IMPORTANT: The use of codified attribute definitions is important as those definitions can be used in both category and product attributes. This commonality provides the ability to define search facets from the category attributes and match those to products that have the same attribute definition.

=== Product Attribute Values
The product attibutes are used to define characteristics (The "material" for a shirt might be "cotton" or "nylon"). The assigned value of that attribute that does not change, regardless of which variant might be selected is called a "product attribute value".

=== Variant Attribute Values
Any product attributes that are specific to the variants of that product are stored at the variant level. (The "size" attribute is assigned to a shirt, and the value for that size "small", "medium", or "large" is associated with a product variant.)

=== Product Options
A product option is represented almost identically to a product attribute but represents a "customization" that can be made to a product variant that does NOT change the variant's SKU. The best way to distinguish between an attribute and an option is to think of a simple use case:

A Shirt has a size and a color and also allows a customer to select a name that will be printed on the back of the shirt. The "size" and "color" are product attributes and each combination of those two will result in a different product variant. The "name" is a customization that will be applied to item variant (by the vendor/manufacturer).

== Product Taxonomy

A product taxonomy is a hierarchical classification system where products are grouped into categories/sub-categories. A taxonomy is codified and can be linked to one or more channels. A taxonomy and a product catalog are closely related, however, there are differences between the two. A product can only be placed once within a taxonomy's category tree whereas a product can be placed in multiple categories within a product catalog. A taxonomy can be used to standardized the set of attributes required for product classification and is appropriate for driving an SEO strategy. The concept of a catalog is typically used for site navigation and driven by merchandising-based analytics.

=== Taxonomy Category

Categories are arranged in a hierarchy where the top-level category is associated with the product taxonomy. The top-level category is called the "root category" and acts as the "parent" for the entire category hierarchy.

The root category contains a set of sub-categories that can be used to drill-down into more specific groupings and each sub-category can also have sub-categories. The hierarchy can be arbitrarily nested but referenced architectures are typically 3 to 5 levels deep.

Each category may contain an optional set of products references allowing products to be grouped into that category.

=== Taxonomy Category Attributes

A category can have one or more "attributes" associated with it. These attributes represent characteristics common to products that can be associated (or will be added) to the category. A category attribute is linked to codified attribute definitions that can be reused by both categories and products.

IMPORTANT: The use of codified attribute definitions is important as those definitions can be used in both category and product attributes. This commonality provides the ability to define search facets from the category attributes and match those to products that have the same attribute definition.

IMPORTANT: "Attributes are to be re-used across the whole category tree and are stand alone. They are never too accurate, so don’t hesitate to have “Diameter of watch dial” and “Diameter of bicycle wheel”, rather than a global “Diameter”. That will strengthen your data consistency (maybe not all diameters are commonly expressed in the same unit), enhance the ease of use of people within your organization, as well as improve clarity for customers."

=== Product Catalog

A product catalog is the "front facing" hierarchy that drive's a storefront's navigation system. There is a strong relationship between the product taxonomy, in that the product catalog can be derived from a taxonomy, however, unlike a taxonomy, a product may be placed multiple times within the catalog. The product catalog is curated and maintained to support branding, merchandising, and promotions of products within the store.

=== Product Catalog Category

A category within a the product catalog can be derived using search expressions against the product taxonomy. The category attributes are tied to the same set of attribute definitions used within the taxonomy and product domains.

== Product Pricing

The pricing of products is really a marketing/merchandising function, however, it is important to provide price syndication such that down stream systems are notified of any price changes.

A pricing "profile" represents the retail pricing for products and allows for different pricing across stores and/or for consumer groups (Example: pros vs non-pros).

- Pricing Profiles/Pricebooks

=== Participation System

The Participation System enables creating scheduled effects on products, including setting the Sale ID and discounting prices.

- See the link:product-streams/product-participation-engine/README.adoc[Participation documention].

NOTE: The Participation System is not yet based on a streaming architecture.


== Product Inventory

IMPORTANT: We have not yet started modeling product inventory

The inventory feed may/may not belong in the product service, as an argument can be made that it might be better to locate this feed within the order management system. For now, we will assume the inventory will be hosted in this service but will be modularized (and encapsulated) to make it easy to move.

- Vendor Inventory

== Related Data

Related data consists of domain concepts that are not directly managed by the product service but required to support the business use cases. These types of domains are imported "copies" of data that may be managed by a separate system.

=== Business Units

A business unit is an organization entity within Ferguson which might have different operational and financial rules. A business unit can have one or more channels associated with it.

NOTE: Each "brand" (Build, Supply, etc) will be represented as a business unit.

=== Channels

A channel represents a distinct distribution channel, within a given business unit, through which products are sold and/or syndicated. A channel can represent a product inventory sold through a web store front, a third-party marketplace, or an SEO classification system.

Important Notes About Channels:

- Two channels within a business unit can represent a different "tenant" in a multi-tenant environment. This is important when you consider that a business unit may have two store fronts that serve different classes of users (Example: buid.com vs faucetsdirect.com).
- A business unit may have a channel for the web store front and a second channel for selling that storefront's inventory through a third-party marketplace such as Amazon.
- Each channel may have different product taxonomies, pricing, and available vendors.
- A channel can have exactly one product taxonomy associated with it. One channel might be used to defined a web storefront's master product data. A second channel can be used to model a web store's site navigation system that allows a product to be placed into multiple catagories.

=== Manufacturers

Each product will be associated with its manufacturer.

=== Vendors

IMPORTANT: We have not yet started modeling vendors.

Vendors are third-parties that are selling the products, used only in the inventory feeds.

== Mapping Build/Supply Concepts

There are established tools and processes used by our "brands" and it is important that we enumerate how those existing concepts will be mapped into the new product domain service.

=== Type, Application, and Handletype

Build.com has a psuedo taxonomy structure that consists of a "type", an "application", and a "handle type". These were originally defined when Build.com was primary selling faucets and over time, this classification system has been expanded to other product type. The "TAH" structure is also mapped/linked to a classification system used by the data team's "standards database".

This structure will be imported into the product domain service as a "master" product catalog where the classification structure is type->application->handletype.

IMPORTANT: If you hear the term "tah", this is referring to the legacy product classification within the type->application->handle type in the master product catalog. Every product sold by build.com is assigned a "tah" value. The quality of the data structured in the existing "type", "applicaiton", and "handle types" varies widely.

=== Build Terms to Product Domain Terms

.Terminology Mapping
|===
|Build.com Term |Product Domain Term|Description
|Finish |Product Variant |A product finish/variant is a tangible unit of merchandise that has a specific name, part number, size, price, and any other attribute required to make the merchandise “sellable”.
|Product Specification |Product Attribute| A product specification is synomymous with a product attribute and is used to describe a specific characteristic about the product.
|Category| Catalog & Taxonomy Category| The term "Category" can be used both when describing a category within the context of a taxonomy and when describing a category with a site's navigation system. It is important to establish a clear, unambiguous definition of both concepts. A "taxonomy category" is structured such that a product can only belong to exactly one category. A "product catalog category" may be derived from the product taxonomy and a product may be mapped into multiple locations.
|===
