logging:
  level:
    ROOT: error
    com.ferguson.cs: warn

info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

spring:
  main:
    allow-bean-definition-overriding: true
