= Participation Engine
:toc: macro
:sectlinks:
:sectanchors:
:stylesheet: ../../asciidoctor.css
:imagesdir: ../../images

toc::[]

== Documentation Links

* link:docs/system-overview.adoc[Participation System Overview]
* link:docs/scenario-tests.adoc[Scenario Tests]
* link:docs/load-testing.adoc[Load Testing]

== Production / Runbook

* Also see link:https://wiki.build.com/display/CON/Participations+and+Product+Pricing+Runbook[production issues / runbook] &nearr; information on the wiki.

=== Monitoring

New Relic is instrumented to record transactions for publish, unpublish, activate, and deactivate events. Within each transaction type,  exceptions from code logic, network errors, database errors, etc, are noticed and associated with the transaction in which they occur.

Participation-related events in NR are recorded as non-web transactions.

* link:++https://one.newrelic.com/launcher/nr1-core.explorer?launcher=eyJzZWxlY3RlZEluc3RhbmNlIjpudWxsfQ==&pane=eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMub3ZlcnZpZXciLCJlbnRpdHlJZCI6Ik1UUTVORGN4ZkVGUVRYeEJVRkJNU1VOQlZFbFBUbncyTmprME9Ua3lOamsifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVFE1TkRjeGZFRlFUWHhCVUZCTVNVTkJWRWxQVG53Mk5qazBPVGt5TmprIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImFwbS1uZXJkbGV0cy5vdmVydmlldyJ9fQ==&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true&platform[filters]=IihuYW1lIGxpa2UgJ3BhcnRpY2knIG9yIGlkID0gJ3BhcnRpY2knIG9yIGRvbWFpbklkID0gJ3BhcnRpY2knKSI=++[Production application overview in New Relic]
* link:++https://one.newrelic.com/launcher/infra.infra?pane=eyJuZXJkbGV0SWQiOiJpbmZyYS5ob3N0cyIsImZlYXR1cmUiOiJzeXN0ZW0iLCJob3N0c0ZpbHRlcnMiOnsiYW5kIjpbeyJvciI6W3sibGlrZSI6eyJhcG1BcHBsaWNhdGlvbk5hbWVzIjoifHBhcnRpY2lwYXRpb24tZW5naW5lIChUZXN0KXwifX0seyJsaWtlIjp7ImFwbUFwcGxpY2F0aW9uTmFtZXMiOiJ8cGFydGljaXBhdGlvbi1lbmdpbmUgKERldmVsb3BtZW50KXwifX0seyJsaWtlIjp7ImFwbUFwcGxpY2F0aW9uTmFtZXMiOiJ8cGFydGljaXBhdGlvbi1lbmdpbmV8In19XX1dfX0&platform[timeRange][duration]=1800000&platform[accountId]=149471++[Infrastructure pages in New Relic for all servers]

=== Configuration

See https://github.com/buildcom/config/blob/master/apps/product-services-participation-engine.yml[configuration properties] &nearr; on github for the current application configuration.

== Development [[development]]

=== Local Run Configuration

This is a persistent application, as opposed to a data flow application that runs once and then stops. When running, it will continue to poll for events periodically. Use your IDE stop button to stop the application or ctrl-c if running in the terminal.

.To run locally, add a Spring Boot run configuration:
* Use `com.ferguson.cs.product.stream.participation.engine.ParticipationEngineApplication` for the main class.
* Enter desired VM options (see table below).

=== Database

The engine makes direct connections to MongoDB and SQL servers.

==== MongoDB and SQL

There is one development MongoDB server, and three dev SQL servers. Because of this, regardless of which SQL database is used, the same set of Participation records are processed on each run.

These practices should be followed when not using cicdev1 to avoid missing or incorrect data, or when using cicdev1 after using a different database:

* Run Services locally, connecting to the same database you will use in the engine, and run Construct locally so that it connects to your local services. Construct _will_ connect automatically with its default localdev profile but may switch to dev Services if the connection to your local Services is lost or if you pause in a breakpoint for too long; using local profile will force it to stay connected to your local services.
* If you want to use a Participation that was published or activated in a different SQL database, then unpublish it and publish it again, to ensure the data is in your configured database when you run the engine.
* Also consider manually cleaning up SQL data for specific Participation records being used for development. See link:docs/load-testing.adoc[load testing] for more information.

=== Log output

The engine emits a log message for each event handled at the INFO level. Additional engine logging can be enabled at DEBUG level.

=== Load Testing

When test mode is enabled, participations below a given id are omitted from processing. This allows running the engine on only your load testing Participation records, omitting any other records present in the database. Also useful when during development.

* See link:docs/load-testing.adoc[load testing docs].

=== Configuration properties

* See current link:https://github.com/buildcom/config/blob/master/apps/product-services-participation-engine.yml[configuration properties] &nearr; in the configuration repo.
* See link:src/test/resources/application-unit.yml[application-unit.yml] for unit / integration test config.

.Configuration for running locally
|===
|Config|Effect|VM Arguments

|SQL Database
|Use CICDEV1
|(_dev default_) `jdbc:sqlserver://chico-db-stable.build.internal\CICDEV1;selectMethod=direct;applicationName=participation-engine;sendStringParametersAsUnicode=false`

|SQL Database
|Use CICDEV2
a|(_localdev default_) `-Ddatasource.core.url="jdbc:sqlserver://chico-db-dev.build.internal\CICDEV2;selectMethod=direct;applicationName=participation-engine;sendStringParametersAsUnicode=false"`

|SQL Database
|Use CICDEV3
a|`-Ddatasource.core.url="jdbc:sqlserver://chico-db-debug.build.internal\CICDEV3;selectMethod=direct;applicationName=participation-engine;sendStringParametersAsUnicode=false"`

|MongoDB Database
|Custom MongoDB server
a|`-Dspring.data.mongodb.uri=mongodb://XXXXXX`

|MongoDB Database
|Use mongo-dev-1
a|(_localdev / dev default_) `-Dspring.data.mongodb.uri=mongodb://mongodb-dev-1.build.internal:27017`

|Application Port
|Specify port to run on
a|(to avoid clashing with services)`-Dserver.port=8081`

|Logging
|Debug steps performed by the engine
a|`-Dlogging.level.com.ferguson.cs=DEBUG -Dlogging.level.com.ferguson.cs.product.stream.participation.engine.data=INFO -Dlogging.level.com.ferguson.cs.product.stream.participation.engine.ParticipationServiceImpl=DEBUG`

|Logging
|Show transactions
a|`-Dlogging.level.org.springframework.transaction.interceptor=TRACE`

|Load Testing
|Restrict records processed for load testing/development
a|`-DparticipationEngine.testModeEnabled=true -DparticipationEngine.testModeMinParticipationId=50000` (only process records with id >= 50000)

|Config source
|Use a config repository branch
a|`-Dspring.cloud.config.label=SODEV-XXXXX`

|Profile
|Change the spring profile
a|Runs with `localdev` by default. You should not need to change it. +
`-Dspring.profiles.active=XXXXX`

|===

=== New Relic configuration for local development

You can configure and use the New Relic java agent locally. This is needed e.g. when modifying the New Relic instrumentation in the app. This is not needed for development or to run the engine locally unless you want to modify or test the NR instrumentation or simply to see your local engine transactions in NR.

When configured, engine events and any errors from your local instance will show up in the `participation-engine (Development)` service in New Relic.

You will need to select your computer name or whatever host on which you are running the engine locally, in the Instances menu in NR. This will filter to only your events.

==== Set up and usage steps

1. Copy the NR license key from the right-hand sidebar under `License Key:` at https://rpm.newrelic.com/accounts/149471. Treat this like you would a password, and do not paste it in chat or commit it to any repositories.
2. Download the new relic java agent jar from https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes. The current version is 5.14 but a newer version should work fine. If you make any changes requiring changes that are in a later version, you'll have to ask SRE to update NR on the participation-engine hosts to the required version.
    a. Put the downloaded `newrelic.jar` file at the top level in your project directory or set the location in the setting below.
    b. Ensure that it's not a sibling of the `newrelic.yml` file that comes with the download (to avoid its settings from colliding with the settings below).
3. Add the configuration params below to your run configuration in your IDE. If running on the command line with `java -jar ...`, add the params there.
    a. Do not modify the `app_name`.
    b. Be sure to use double quotes on the param values.
4. Start up the app and check that it starts correctly and has some INFO log entries from the NR agent. It will also show the location of its log file, which will be a sibling of the `newrelic.jar` file unless configured differently. If you have any problems it's good to check the log file.
5. Generate some events / errors.
6. To find the Services page for the engine, browse to NR, select `APM`, filter by `participation`, and choose `participation-engine (Development)`. Or navigate directly to link:++https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMub3ZlcnZpZXciLCJlbnRpdHlJZCI6Ik1UUTVORGN4ZkVGUVRYeEJVRkJNU1VOQlZFbFBUbncyTmpJMU1qUTROalUiLCJ0cmFuc2FjdGlvblR5cGUiOnsidHJhbnNhY3Rpb25UeXBlIjoiT3RoZXIifX0=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVFE1TkRjeGZFRlFUWHhCVUZCTVNVTkJWRWxQVG53Mk5qSTFNalE0TmpVIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImFwbS1uZXJkbGV0cy5vdmVydmlldyJ9fQ==&platform[timeRange][duration]=3600000&platform[$isFallbackTimeRange]=false&platform[filters]=IihuYW1lIGxpa2UgJ3BhcnRpY2knIG9yIGlkID0gJ3BhcnRpY2knIG9yIGRvbWFpbklkID0gJ3BhcnRpY2knKSI=&platform[accountId]=149471++[that page].
7. You can also look at the servers directly, by navigating to `Infrastructure` then using the `FILTER HOSTS >` button on the left sidebar and filtering by `participation`.

.Configuration to enable New Relic locally.
[source]
----
-Dnewrelic.config.license_key="${the NR license key you copied}"
-Dnewrelic.config.app_name="participation-engine (Development)"
-javaagent:./newrelic.jar
----

=== Development / Debugging

* See link:docs/developer-helpers.adoc[Development / Debugging]
