logging:
  level:
    ROOT: ERROR
    org.springframework: WARN
    org.springframework.cloud: WARN
    org.springframework.web: INFO
    com.build: INFO

info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

spring:
  main:
    allow-bean-definition-overriding: true
