---
logging:
  level:
    ROOT: info
    com.build: info

info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

spring:
  main:
    allow-bean-definition-overriding: true