CREATE TABLE unit_of_measure (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code VARCHAR(10) UNIQUE,
	name VARCHAR(60),
	description VARCHAR(200),
	created_timestamp TIMESTAMP,
	last_modified_timestamp TIMESTAMP,
	version SMALLINT
);

CREATE TABLE attribute_definition (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code VARCHAR(10) UNIQUE,
	datatype VARCHAR(20),
	description VARCHAR(200),
	unit_of_measure_id INTEGER,
	minimum_value VARCHAR(60),
	maximum_value VARCHAR(60),
	created_timestamp TIMESTAMP,
	last_modified_timestamp TIMESTAMP,
	version SMALLINT,
	CONSTRAINT unit_of_measure_fk FOREIGN KEY (unit_of_measure_id) REFERENCES unit_of_measure(id)
);

CREATE TABLE attribute_definition_value (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	attribute_definition_id INTEGER,
	value VARCHAR(60),
	display_value VARCHAR(60),
	CONSTRAINT attribute_definition_fk FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition(id)
);

CREATE TABLE taxonomy (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code VARCHAR(10) UNIQUE,
	description VARCHAR(200),
	category_id INTEGER,
	created_timestamp TIMESTAMP,
	last_modified_timestamp TIMESTAMP,
	version SMALLINT
);

CREATE TABLE taxonomy_category (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	taxonomy_id INTEGER,
	code VARCHAR(10) UNIQUE,
	name VARCHAR(60),
	path VARCHAR(600),
	description VARCHAR(200),
	category_parent_id INTEGER,
	created_timestamp TIMESTAMP,
	last_modified_timestamp TIMESTAMP,	
	version SMALLINT,
	CONSTRAINT taxonomy_fk FOREIGN KEY (taxonomy_id) REFERENCES taxonomy(id),
	CONSTRAINT parent_category_fk FOREIGN KEY (category_parent_id) REFERENCES taxonomy_category(id)
);
CREATE TABLE taxonomy_category_attribute(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	taxonomy_category_id INTEGER,
	attribute_definition_id INTEGER,
	is_hidden BOOLEAN,
	is_required BOOLEAN,
	CONSTRAINT taxonomy_category_fk FOREIGN KEY (taxonomy_category_id) REFERENCES taxonomy_category(id),
	CONSTRAINT attribute_definition_fk FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition(id)
);
CREATE TABLE taxonomy_category_product(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	taxonomy_category_id INTEGER,
	product_id INTEGER,
	CONSTRAINT taxonomy_category_fk FOREIGN KEY (taxonomy_category_id) REFERENCES taxonomy_category(id)
);


CREATE TABLE channel (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code VARCHAR(10) UNIQUE,
	description VARCHAR(200),
	channel_type VARCHAR(20),
	business_unit VARCHAR(20),
	is_active BOOLEAN,
	taxonomy_id INTEGER,
	created_timestamp TIMESTAMP,
	last_modified_timestamp TIMESTAMP,
	version SMALLINT,
	CONSTRAINT taxonomy_fk FOREIGN KEY (taxonomy_id) REFERENCES taxonomy(id)
);

