participation-engine:
  task-user-id: 835
  schedule-fixed-delay: 1000
  schedule-initial-delay: 2000
  test-mode-enabled: true
  test-mode-min-participation-id: 5000

logging:
  level:
    ROOT: ERROR
    org.springframework: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    com.ferguson.cs: INFO

info:
  build:
    artifact: "@project.build.finalName@"
    version: "@project.version@"

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /app
      exposure:
        include: loggers,health
  endpoint:
    health:
      enabled: true
    loggers:
      enabled: true

---

spring:
  profiles: dev,test,production

participation-engine:
  testmode-enabled: false
