

logging:
  level:
    ROOT: ERROR
    org.springframework: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    com.build: INFO

info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

management:
  security:
    enabled: false

datasource:
  # Development
  core:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://chico-db-dev.build.internal\CICDEV2;selectMethod=direct;applicationName=omc;sendStringParametersAsUnicode=false
    jdbc-url: jdbc:sqlserver://chico-db-dev.build.internal\CICDEV2;selectMethod=direct;applicationName=omc;sendStringParametersAsUnicode=false
    username: wbsrvr_mmc
    password: 'Build12Dot24Cow!'
  reporter:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://chico-db-dev.build.internal\CICDEV2;selectMethod=direct;applicationName=omc;sendStringParametersAsUnicode=false
    jdbc-url: jdbc:sqlserver://chico-db-dev.build.internal\CICDEV2;selectMethod=direct;applicationName=omc;sendStringParametersAsUnicode=false
    username: wbsrvr_mmc
    password: 'Build12Dot24Cow!'
sample:
  # It is ok for initial config to be here however it should be moved to the config server
  localFilePath: ./
spring:
  main:
    allow-bean-definition-overriding: true
