logging:
  level:
    ROOT: ERROR
    org.springframework: WARN
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    com.build: INFO

info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

management:
  security:
    enabled: false

sample:
  # It is ok for initial config to be here however it should be moved to the config server
  localFilePath: ./
spring:
  main:
    allow-bean-definition-overriding: true
