---
logging:
  level:
    ROOT: info

spring:
    data:
      mongodb:
        database: products
        uri: mongodb://${docker.hostname:localhost}
    jackson:
      default-property-inclusion:  NON_NULL
