---
logging:
  level:
    ROOT: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    com.ferguson.cs.product.dao.attribute: trace
spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/product
      username: 'product'
      password: 'product'
    jackson:
      default-property-inclusion: non-null
mybatis:
  type-aliases-package: com.ferguson.cs.model
  type-handlers-package: com.ferguson.cs.typehandler