---
logging:
  level:
    ROOT: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    com.ferguson.cs.product.dao: trace
spring:
    datasource:
        # Postgres connection information.
#      url: jdbc:postgresql://localhost:5432/product
#      username: 'product'
#      password: 'product'

      # SQL Server
      url: jdbc:sqlserver://localhost;database=product;applicationName=product-service;sendStringParametersAsUnicode=false
      username: 'sa'
      password: 'Your_password123'
    jackson:
      default-property-inclusion: non-null
mybatis:
  type-aliases-package: com.ferguson.cs.model
  type-handlers-package: com.ferguson.cs.typehandler