---
logging:
  level:
    ROOT: info
    com.build: info

spring:
  mvc:
    favicon:
      enabled: false
  jmx:
    default-domain: com.build

info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
